image: ruby:2.3

before_script:
  - apt-get update >/dev/null
  - apt-get install -y locales >/dev/null
  - echo "en_GB UTF-8" > /etc/locale.gen
  - locale-gen en_GB.UTF-8
  - export LANG=en_GB.UTF-8
  - export LANGUAGE=en_GB:en
  - export LC_ALL=en_GB.UTF-8
  
pages:
  script:
  - gem install jekyll
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
