name: Mr P Sharp
<<<<<<< Updated upstream
host: 10.0.1.3
port: 8888
=======
host: ganymede.mrpsharp.org
port: 8080
>>>>>>> Stashed changes
markdown: kramdown
exclude: ["*.aux", "*.log", "*.toc", "*.out", "*.tex"]
